Repository exoego/aws-lambda-scalajs-facade, pull requests merged in 2020-02, with the labels that each got.

#78 Update sbt to 1.3.8
  project/build.properties
Labels: chore

#79 Auto merging dependencies update
  .mergify.yml
Labels: chore

#84 Handler[T,R] should be newable/extendable in newer Scala.js
  README.md
  src/main/scala/net/exoego/facade/aws_lambda/Handler.scala
  src/main/scala/net/exoego/facade/aws_lambda/package.scala
Labels: enhancement

#85 Remove unused type aliases
  src/main/scala/net/exoego/facade/aws_lambda/package.scala
Labels: enhancement

#86 mistyping: js.Error instead of scala.Error
  src/main/scala/net/exoego/facade/aws_lambda/Types.scala
  src/main/scala/net/exoego/facade/aws_lambda/package.scala
Labels: bug

#87 Refine Cloudfront stuffs
  src/main/scala/net/exoego/facade/aws_lambda/Types.scala
  src/main/scala/net/exoego/facade/aws_lambda/package.scala
Labels: enhancement

#88 Refine Lex
  src/main/scala/net/exoego/facade/aws_lambda/Types.scala
Labels: enhancement

#89 Split up package
  src/main/scala/net/exoego/facade/aws_lambda/AuthResponseContext.scala
  src/main/scala/net/exoego/facade/aws_lambda/Handler.scala
  src/main/scala/net/exoego/facade/aws_lambda/Types.scala
  src/main/scala/net/exoego/facade/aws_lambda/alb/alb.scala
  src/main/scala/net/exoego/facade/aws_lambda/alb/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/apigateway/apigateway.scala
  src/main/scala/net/exoego/facade/aws_lambda/apigateway/authorizer/authorizer.scala
  src/main/scala/net/exoego/facade/aws_lambda/apigateway/authorizer/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/apigateway/proxy/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/apigateway/proxy/proxy.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudformation/customresource/customresource.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudformation/customresource/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudfront/cloudfront.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudfront/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudfront/request/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudfront/request/request.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudfront/response/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudfront/response/response.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudwatch/events/events.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudwatch/events/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudwatch/logs/logs.scala
  src/main/scala/net/exoego/facade/aws_lambda/cloudwatch/logs/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/action/action.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/action/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/pipeline/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/pipeline/pipeline.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/stage/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/cloudwatch/stage/stage.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/codepipeline.scala
  src/main/scala/net/exoego/facade/aws_lambda/codepipeline/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/cognitouserpool/cognitouserpool.scala
  src/main/scala/net/exoego/facade/aws_lambda/cognitouserpool/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/dynamodbstream/dynamodbstream.scala
  src/main/scala/net/exoego/facade/aws_lambda/dynamodbstream/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/firehose/firehosetransformation.scala
  src/main/scala/net/exoego/facade/aws_lambda/firehose/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/kinesisstream/kinesisstream.scala
  src/main/scala/net/exoego/facade/aws_lambda/kinesisstream/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/lex/lex.scala
  src/main/scala/net/exoego/facade/aws_lambda/lex/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/s3/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/s3/s3.scala
  src/main/scala/net/exoego/facade/aws_lambda/s3batch/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/s3batch/s3batch.scala
  src/main/scala/net/exoego/facade/aws_lambda/sns/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/sns/sns.scala
  src/main/scala/net/exoego/facade/aws_lambda/sqs/package.scala
  src/main/scala/net/exoego/facade/aws_lambda/sqs/sqs.scala
Labels: enhancement

#91 Release 0.5.0
  README.md
  version.sbt
Labels: chore

#92 Enable release-drafter
  .github/release-drafter.yml
Labels: chore

#93 Drop nodejs v8 since its LTS reached EOL
  README.md
Labels: documentation

#96 Cross-publishing for Scala.js 1.0/0.6
  .github/workflows/format.yml
  .mergify.yml
  .travis.yml
  README.md
  build.sbt
  project/plugins.sbt
  publishing.sbt
  release.sh
  scripts/release.sh
  version.sbt
Labels: enhancement

#97 Set snapshot version
  version.sbt
Labels: chore

#99 Add protocol to APIGatewayEventRequestContext
  src/main/scala/net/exoego/facade/aws_lambda/apigateway.scala
Labels: enhancement
